version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=simple
      - MYSQL_DATABASE=adp

  backend:
    image: "dineshsonachalam/adp-ny-hackathon-backend:latest"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - frontend
    ports:
      - "8084:8084"
    depends_on:
      - mysql
         
  frontend:
    image: "dineshsonachalam/adp-ny-hackathon-frontend:latest"
    networks:
      - frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - mysql
networks:
  frontend: