version: '3'
services:
  postgres:
    image: "postgres:12"
    networks:
      - frontend
    ports:
      - "5432:5432"
    restart: always
    user: 1000:1000
    environment:
      - POSTGRES_USER=dinesh
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=dinesh-micro-apps
    volumes:
      - ./backend/adp.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data/
  
  backend:
    image: "dineshsonachalam/netflix-hackathon-backend:latest"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - frontend
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      
networks:
  frontend: