version: '3'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    networks:
      - frontend
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=simple

  backend:
    image: "dineshsonachalam/adp-ny-hackathon-backend:latest"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - frontend
    ports:
      - "8001:8001"
    depends_on:
      - mysql
      
networks:
  frontend: