namespace: dinesh
replicas: 1

adpBackend:
    image: dineshsonachalam/adp-ny-hackathon-backend:latest
    containerPort: 8001
    appName: adp-backend
    ingressRoute: (Host(`api-adp.dineshsonachalam.com`))

adpFrontend:
    image: dineshsonachalam/adp-ny-hackathon-frontend:latest
    containerPort: 3000   
    appName: adp-frontend
    ingressRoute: (Host(`adp.dineshsonachalam.com`))



