namespace: dinesh
replicas: 1

nfBackend:
    image: dineshsonachalam/netflix-hackathon-backend:latest
    containerPort: 8001
    appName: nf-backend
    ingressRoute: (Host(`api-netflix.dineshsonachalam.com`))

nfFrontend:
    image: dineshsonachalam/netflix-hackathon-frontend:latest
    containerPort: 3000   
    appName: nf-frontend
    ingressRoute: (Host(`netflix.dineshsonachalam.com`))



